// Generated by js_of_ocaml
//# buildInfo:effects=false, use-js-string=false, version=5.0.1
(function
   (globalThis)
   {"use strict";
    var runtime=globalThis.jsoo_runtime;
    function caml_call1(f,a0)
     {return f.length == 1?f(a0):runtime.caml_call_gen(f,[a0])}
    var
     global_data=runtime.caml_get_global_data(),
     cst_hello_from_js=runtime.caml_string_of_jsbytes("hello from js"),
     Stdlib=global_data.Stdlib;
    caml_call1(Stdlib[46],cst_hello_from_js);
    var Dune_exe_Foo=[0];
    runtime.caml_register_global(2,Dune_exe_Foo,"Dune__exe__Foo");
    return}
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiIuZm9vLmVvYmpzL2J5dGUvZHVuZV9fZXhlX19Gb28uY21vLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbXSwic291cmNlcyI6WyIvVXNlcnMvYXphdC9EZXNrdG9wL1Byb2plY3RzL0VmaW0tdG9wL09DYW5yZW4tYmFzaWMtdGVtcGxhdGUvX2J1aWxkL2RlZmF1bHQvZGVtbzFwcHgvZm9vLm1sIl0sIm1hcHBpbmdzIjoiOzs7OztJOzs7Ozs7O0lBQUE7OztVIiwic291cmNlc0NvbnRlbnQiOlsicHJpbnRfZW5kbGluZSBcImhlbGxvIGZyb20ganNcIlxuIl19
